import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'
import MessagePopup from '@/component/MessagePopup.client'
import I18NProvider from '@/provider/I18NProvider'
import ReactQueryProvider from '@/provider/ReactQueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout(props: Props) {
  const { children, locale } = props

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <I18NProvider locale={locale}>{children}</I18NProvider>
        </ReactQueryProvider>
        <MessagePopup />
      </body>
    </html>
  )
}

type Props = Readonly<{
  children: React.ReactNode
  locale: string
}>
